DEBUG 2023-07-09 09:05:28.734 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-07-09 09:05:28.734 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-07-09 09:05:28.734 UTC: 	 Executing command: 'status'
DEBUG 2023-07-09 09:05:28.734 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/skeshri/.crab3
ERROR 2023-07-09 09:05:28.735 UTC: 	 Error: rab_369978_Muon1 is not a valid CRAB project directory.
ERROR 2023-07-09 09:05:28.735 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: rab_369978_Muon1 is not a valid CRAB project directory.
INFO 2023-07-09 09:05:28.737 UTC: 	 Log file is /afs/cern.ch/work/s/skeshri/GEM_efficiency/Ntuple/CMSSW_13_0_9/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2023-07-09 09:05:33.845 UTC: 	 CRAB Client version: v3.230417
DEBUG 2023-07-09 09:05:33.845 UTC: 	 Running on: Linux lxplus774.cern.ch 3.10.0-1160.90.1.el7.x86_64 #1 SMP Thu May 4 15:21:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-07-09 09:05:33.845 UTC: 	 Executing command: 'status'
DEBUG 2023-07-09 09:05:33.845 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/skeshri/.crab3
ERROR 2023-07-09 09:05:33.846 UTC: 	 Error: rab_369978_Muon1 is not a valid CRAB project directory.
ERROR 2023-07-09 09:05:33.846 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230417.01/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: rab_369978_Muon1 is not a valid CRAB project directory.
INFO 2023-07-09 09:05:33.847 UTC: 	 Log file is /afs/cern.ch/work/s/skeshri/GEM_efficiency/Ntuple/CMSSW_13_0_9/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2023-10-11 10:28:47.597 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-10-11 10:28:47.597 UTC: 	 Running on: Linux lxplus717.cern.ch 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-10-11 10:28:47.597 UTC: 	 Executing command: 'submit'
DEBUG 2023-10-11 10:28:47.597 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/skeshri/.crab3
DEBUG 2023-10-11 10:28:47.598 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2023-10-11 11:12:08.296 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-10-11 11:12:08.296 UTC: 	 Running on: Linux lxplus717.cern.ch 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-10-11 11:12:08.296 UTC: 	 Executing command: 'status'
DEBUG 2023-10-11 11:12:08.296 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/skeshri/.crab3
ERROR 2023-10-11 11:12:08.297 UTC: 	 Error: crab_20231011_13 is not a valid CRAB project directory.
ERROR 2023-10-11 11:12:08.297 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 159, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/bin/crab.py", line 144, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 275, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.230612.00/lib/CRABClient/Commands/SubCommand.py", line 642, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_20231011_13 is not a valid CRAB project directory.
INFO 2023-10-11 11:12:08.300 UTC: 	 Log file is /afs/cern.ch/work/s/skeshri/GEM_efficiency/Ntuple/HI/CMSSW_13_2_5_patch3/src/MuDPGAnalysis/MuonDPGNtuples/CRAB_SUB/crab.log
DEBUG 2023-10-22 08:53:49.903 UTC: 	 CRAB Client version: v3.230612
DEBUG 2023-10-22 08:53:49.903 UTC: 	 Running on: Linux lxplus717.cern.ch 3.10.0-1160.99.1.el7.x86_64 #1 SMP Wed Sep 13 14:19:20 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2023-10-22 08:53:49.903 UTC: 	 Executing command: 'submit'
DEBUG 2023-10-22 08:53:49.905 UTC: 	 Found CRAB cache file /afs/cern.ch/user/s/skeshri/.crab3
DEBUG 2023-10-22 08:53:49.905 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
